### PR TITLE
Update nvidiawayland.mdx

### PR DESCRIPTION
**Pull request by pfelrodrigues**
Fix error typo.

Signed-off-by: Paulo Rodrigues <paulo@rodrigues.pw>

### CODE REVIEW

**Comment by SomethingGeneric** [comment]
LGTM

**Comment by mrshmllow** [comment]
no it doesn't

**Comment by mrshmllow** [comment]
:(

**Comment by mchalunderscore** [comment]
For future reference @SomethingGeneric work is currently being done on the `i18n` branch

**Comment by SomethingGeneric** [comment]
_oh shoot my bad_

**Pull request merged**
