### PR TITLE
Rework of the NVIIDA Wayland guide

### PR DESCRIPTION
**Pull request by orowith2os**
Signed-off-by: Oro <93224879+orowith2os@users.noreply.github.com>

### CODE REVIEW

**Comment by fries1234** [comment]
proper grammar is hard :pensive:

**Review by fries1234 — APPROVED** [review]

**Comment by orowith2os** [comment]
bleh, gotta rename the file on the branch. One moment.

**Comment by orowith2os** [comment]
...well, git is fun.

**Comment by mrshmllow** [comment]
fixed that for you

**Pull request merged**
